server:
  port: 8060
    
vietin:
  onefinPrivateKey: D:\\Project\\keys\\onefin-privatekey-uat-vietin.der
  vtbPublicKey: /app/onefin/keys/Vietinbank_publicKey.pem
  version: 1.0
  merchantId: 1444
  providerId: 124
  ibmClientId: 9049dbd1-2f74-4df9-a0c6-4acb50bd3f01
  xIbmClientSecret: uS7pQ2cV4yQ4iK7mT2mF6jH0wU3kA7pQ0lX8mF7kX3jO7kC2wV
  url:
    tokenIssue: https://api-uat.vietinbank.vn/vtb-api-uat/development/v1/ewallet/tokenIssue
    verifyPin: https://api-uat.vietinbank.vn/vtb-api-uat/development/v1/ewallet/verifyPin
    registerOnlinePay: https://api-uat.vietinbank.vn/vtb-api-uat/development/v1/ewallet/registerOnlinePay
    tokenRevoke: https://api-uat.vietinbank.vn/vtb-api-uat/development/v1/ewallet/tokenRevoke
    tokenReissue: https://api-uat.vietinbank.vn/vtb-api-uat/development/v1/ewallet/tokenReIssue
    paymentByToken: https://api-uat.vietinbank.vn/vtb-api-uat/development/v1/ewallet/paymentByToken
    paymentByOTP: https://api-uat.vietinbank.vn/vtb-api-uat/development/v1/ewallet/paymentByOTP

    
logging:
  level:
    root: info
  file: logs/connector-bank.log
